server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 8569
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.board.model
  configuration:
    map-underscore-to-camel-case: true